### PR TITLE
Fix color code

### PR DESCRIPTION
**Pull request by takecy**
Hi :) I continue to love this widget.

Once again, Github's contribution map color code has changed and has the same problem as #16.
I fixed it, please check it :)
I have installed the fixed application and confirmed that it works fine.

### CODE REVIEW

**Comment by pankona** [comment]
@xRoker 

Hello! I'm also one of living this widget 😋 
Recently the widget doesn't work. It seems the cause is the same as #16 as @takecy mentioned.
If you still continue to maintain this awesome product, could you please pull this patch and publish it on PlayStore?

**Review by yeusiukou — APPROVED** [review]
Thank you @takecy! Awesome work!

**Comment by yeusiukou** [comment]
@pankona thanks for pinging me on that, somehow I missed the PR. The fix is available in the Play Store!

**Comment by takecy** [comment]
Thank you for merging and updated app✨

**Pull request merged**
