### PR TITLE
Improve UI

### PR DESCRIPTION
**Pull request by hearsilent**
- Improve UI
- Replace drawable by vector assets
- Fixed Color theme doesn't init value at first time
- Fixed string tune "0 days" -> "0 day"

### CODE REVIEW

**Comment by yeusiukou** [comment]
Hi, @hearsilent ! Thank you for the collaboration! Could you please provide more information on the UI improvements you made?

**Comment by hearsilent** [comment]
I changed 1 \* n and 2 \* 5 UI

# Before

device-2016-10-28-225623
device-2016-10-28-224728

# After

device-2016-10-28-225459
device-2016-10-28-225218

**Comment by hearsilent** [comment]
@xRoker

**Comment by yeusiukou** [comment]
Hi, I'm sorry for the late reply. You replaced the Octocat logo with GitHub. I'm not sure everybody will like it. It would make sense to add a menu in which users can select the logo. What do you think?

**Comment by hearsilent** [comment]
Ok, I agree.
But I'm busy during this month, I'll add it.
When I added, I'll tell you :)

**Comment by yeusiukou** [comment]
Cool, thanks!

**Pull request closed without merging**
